// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wbibjieuxxmezsavjasn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndiaWJqaWV1eHhtZXpzYXZqYXNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczNDk0OTYsImV4cCI6MjA3MjkyNTQ5Nn0.zvvVTpv4Z-6OmsTx0QITL6Yd9WwPsxLo6ave8UYRNMs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});